/**
 * Shader source: https://www.shadertoy.com/view/DlfSz8
 */
#version 460 core

#define CURVATURE 5.1
#define BLUR      0.012
#define CA_AMT    1.012

layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

layout(binding = 0, rgba8) readonly uniform image2D inputImage;
layout(binding = 1, rgba8) writeonly uniform image2D outputImage;

//helper for bilinear image samples
vec4 sampleImage(vec2 uv) {
    ivec2 size = imageSize(inputImage);

    //clamp UVs like a normal clamped texture
    uv = clamp(uv, 0.0, 1.0);

    //convert normalized coordinates to texel space
    vec2 pos = uv * vec2(size) - 0.5;

    ivec2 p0 = ivec2(floor(pos));
    ivec2 p1 = p0 + ivec2(1);

    vec2 f = fract(pos);

    //clamp texel coordinates
    p0 = clamp(p0, ivec2(0), size - 1);
    p1 = clamp(p1, ivec2(0), size - 1);

    //sample texels
    vec4 c00 = imageLoad(inputImage, ivec2(p0.x, p0.y));
    vec4 c10 = imageLoad(inputImage, ivec2(p1.x, p0.y));
    vec4 c01 = imageLoad(inputImage, ivec2(p0.x, p1.y));
    vec4 c11 = imageLoad(inputImage, ivec2(p1.x, p1.y));

    //mix all four samples
    return mix(mix(c00, c10, f.x), mix(c01, c11, f.x), f.y);
}

void main() {
    ivec2 pixel = ivec2(gl_GlobalInvocationID.xy);

    ivec2 resolution = imageSize(outputImage);

    if (pixel.x >= resolution.x ||
        pixel.y >= resolution.y)
    {
        return;
    }

    vec2 fragCoord = vec2(pixel) + 0.5;
    vec2 uv = fragCoord / vec2(resolution);

    //Curving
    vec2 crtUV = uv * 2.0 - 1.0;
    vec2 offset = crtUV.yx / CURVATURE;
    crtUV += crtUV * offset * offset;
    crtUV = crtUV * 0.5 + 0.5;

    //Screen edges
    vec2 edge = smoothstep(vec2(0.0), vec2(BLUR), crtUV) * (1.0 - smoothstep(vec2(1.0 - BLUR), vec2(1.0), crtUV));


    //Chromatic aberration
    vec2 redUV = (crtUV - 0.5) * CA_AMT + 0.5;
    vec2 blueUV = (crtUV - 0.5) / CA_AMT + 0.5;

    float r = sampleImage(redUV).r;
    float g = sampleImage(crtUV).g;
    float b = sampleImage(blueUV).b;

    vec3 color = vec3(r, g, b);

    color *= edge.x * edge.y;

    //Scanlines
    float scan = 0.75 * 0.5 * abs(sin(fragCoord.y));
    color = mix(color, vec3(0.0), scan);

    //Output
    imageStore(outputImage, pixel, vec4(color, 1.0));
}