name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
          submodules: recursive
    - name: install_dependencies
      run: sudo ./installDependencies.sh
    - name: compile
      run: ./runbuild.sh norun
